[package]
name = "bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crepe = "0.1.8"

[dev-dependencies]
crepe = "0.1.8"
criterion = "0.5.1"

[[bench]]
name = "my_bench"
harness = false